/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DeliverabilityTestControllerApi.h
 *
 * 
 */

#ifndef COM_MAILSLURP_CLIENT_API_DeliverabilityTestControllerApi_H_
#define COM_MAILSLURP_CLIENT_API_DeliverabilityTestControllerApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/CreateDeliverabilitySimulationJobOptions.h"
#include "CppRestOpenAPIClient/model/CreateDeliverabilityTestOptions.h"
#include "CppRestOpenAPIClient/model/DeleteResult.h"
#include "CppRestOpenAPIClient/model/DeliverabilityAnalyticsSeriesDto.h"
#include "CppRestOpenAPIClient/model/DeliverabilityEntityResultPageDto.h"
#include "CppRestOpenAPIClient/model/DeliverabilityFailureHotspotsDto.h"
#include "CppRestOpenAPIClient/model/DeliverabilityPollStatusResultDto.h"
#include "CppRestOpenAPIClient/model/DeliverabilitySimulationJobDto.h"
#include "CppRestOpenAPIClient/model/DeliverabilitySimulationJobEventPageDto.h"
#include "CppRestOpenAPIClient/model/DeliverabilityTestDto.h"
#include "CppRestOpenAPIClient/model/DeliverabilityTestPageDto.h"
#include "CppRestOpenAPIClient/model/UpdateDeliverabilityTestOptions.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace com {
namespace mailslurp {
namespace client {
namespace api {

using namespace com::mailslurp::client::model;



class  DeliverabilityTestControllerApi 
{
public:

    explicit DeliverabilityTestControllerApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~DeliverabilityTestControllerApi();

    /// <summary>
    /// Cancel deliverability simulation job
    /// </summary>
    /// <remarks>
    /// Cancel a running or paused simulation job.
    /// </remarks>
    /// <param name="testId"></param>
    /// <param name="jobId"></param>
    pplx::task<std::shared_ptr<DeliverabilitySimulationJobDto>> cancelDeliverabilitySimulationJob(
        utility::string_t testId,
        utility::string_t jobId
    ) const;
    /// <summary>
    /// Create deliverability simulation job
    /// </summary>
    /// <remarks>
    /// Create and start a simulation job for a running deliverability test. Only one active simulation job is allowed per user.
    /// </remarks>
    /// <param name="testId"></param>
    /// <param name="createDeliverabilitySimulationJobOptions"></param>
    pplx::task<std::shared_ptr<DeliverabilitySimulationJobDto>> createDeliverabilitySimulationJob(
        utility::string_t testId,
        std::shared_ptr<CreateDeliverabilitySimulationJobOptions> createDeliverabilitySimulationJobOptions
    ) const;
    /// <summary>
    /// Create deliverability/load test
    /// </summary>
    /// <remarks>
    /// Create a deliverability test for inboxes or phone numbers using ALL, PATTERN, or EXPLICIT selector scope.
    /// </remarks>
    /// <param name="createDeliverabilityTestOptions"></param>
    pplx::task<std::shared_ptr<DeliverabilityTestDto>> createDeliverabilityTest(
        std::shared_ptr<CreateDeliverabilityTestOptions> createDeliverabilityTestOptions
    ) const;
    /// <summary>
    /// Delete deliverability/load test
    /// </summary>
    /// <remarks>
    /// Delete test and all persisted entity-level results.
    /// </remarks>
    /// <param name="testId"></param>
    pplx::task<std::shared_ptr<DeleteResult>> deleteDeliverabilityTest(
        utility::string_t testId
    ) const;
    /// <summary>
    /// Duplicate deliverability/load test
    /// </summary>
    /// <remarks>
    /// Create a fresh deliverability test using an existing test configuration, including selector scope, exclusions, and expectations.
    /// </remarks>
    /// <param name="testId"></param>
    pplx::task<std::shared_ptr<DeliverabilityTestDto>> duplicateDeliverabilityTest(
        utility::string_t testId
    ) const;
    /// <summary>
    /// Export deliverability/load test report as PDF
    /// </summary>
    /// <remarks>
    /// Export a PDF report for a terminal deliverability test (COMPLETE, FAILED, or STOPPED), including configuration, summary outcomes, and detailed entity-level results.
    /// </remarks>
    /// <param name="testId"></param>
    pplx::task<void> exportDeliverabilityTestReport(
        utility::string_t testId
    ) const;
    /// <summary>
    /// Export deliverability/load test entity results as CSV
    /// </summary>
    /// <remarks>
    /// Export per-entity deliverability results including expectation-level pass/fail counts. The latest status is evaluated with the same polling safeguards before export.
    /// </remarks>
    /// <param name="testId"></param>
    /// <param name="matched"> (optional, default to false)</param>
    pplx::task<void> exportDeliverabilityTestResults(
        utility::string_t testId,
        boost::optional<bool> matched
    ) const;
    /// <summary>
    /// Get deliverability analytics time series
    /// </summary>
    /// <remarks>
    /// Compare deliverability runs over a time range with bucketed chart metrics and run-level rows for table views.
    /// </remarks>
    /// <param name="since"> (optional, default to utility::datetime())</param>
    /// <param name="before"> (optional, default to utility::datetime())</param>
    /// <param name="scope"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="bucket"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="runLimit"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<DeliverabilityAnalyticsSeriesDto>> getDeliverabilityAnalyticsSeries(
        boost::optional<utility::datetime> since,
        boost::optional<utility::datetime> before,
        boost::optional<utility::string_t> scope,
        boost::optional<utility::string_t> bucket,
        boost::optional<int32_t> runLimit
    ) const;
    /// <summary>
    /// Get deliverability failure hotspots
    /// </summary>
    /// <remarks>
    /// Find commonly failing entities and phone country/variant dimensions across deliverability runs in a time range.
    /// </remarks>
    /// <param name="since"> (optional, default to utility::datetime())</param>
    /// <param name="before"> (optional, default to utility::datetime())</param>
    /// <param name="scope"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="limit"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<DeliverabilityFailureHotspotsDto>> getDeliverabilityFailureHotspots(
        boost::optional<utility::datetime> since,
        boost::optional<utility::datetime> before,
        boost::optional<utility::string_t> scope,
        boost::optional<int32_t> limit
    ) const;
    /// <summary>
    /// Get deliverability simulation job
    /// </summary>
    /// <remarks>
    /// Get simulation job status and progress counters.
    /// </remarks>
    /// <param name="testId"></param>
    /// <param name="jobId"></param>
    pplx::task<std::shared_ptr<DeliverabilitySimulationJobDto>> getDeliverabilitySimulationJob(
        utility::string_t testId,
        utility::string_t jobId
    ) const;
    /// <summary>
    /// Get deliverability simulation job events
    /// </summary>
    /// <remarks>
    /// Get paged simulation events including send successes and failures.
    /// </remarks>
    /// <param name="testId"></param>
    /// <param name="jobId"></param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="size"> (optional, default to 0)</param>
    /// <param name="sort"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<DeliverabilitySimulationJobEventPageDto>> getDeliverabilitySimulationJobEvents(
        utility::string_t testId,
        utility::string_t jobId,
        boost::optional<int32_t> page,
        boost::optional<int32_t> size,
        boost::optional<utility::string_t> sort
    ) const;
    /// <summary>
    /// Get deliverability/load test
    /// </summary>
    /// <remarks>
    /// Get deliverability test configuration and latest progress counters.
    /// </remarks>
    /// <param name="testId"></param>
    pplx::task<std::shared_ptr<DeliverabilityTestDto>> getDeliverabilityTest(
        utility::string_t testId
    ) const;
    /// <summary>
    /// Get deliverability/load test entity results
    /// </summary>
    /// <remarks>
    /// Get paged per-entity expectation results with optional matched/unmatched filtering.
    /// </remarks>
    /// <param name="testId"></param>
    /// <param name="matched"> (optional, default to false)</param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="size"> (optional, default to 0)</param>
    /// <param name="sort"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<DeliverabilityEntityResultPageDto>> getDeliverabilityTestResults(
        utility::string_t testId,
        boost::optional<bool> matched,
        boost::optional<int32_t> page,
        boost::optional<int32_t> size,
        boost::optional<utility::string_t> sort
    ) const;
    /// <summary>
    /// List deliverability/load tests
    /// </summary>
    /// <remarks>
    /// List deliverability tests for the authenticated account.
    /// </remarks>
    /// <param name="page">Page index (optional, default to 0)</param>
    /// <param name="size">Page size (optional, default to 0)</param>
    /// <param name="sort">Sort direction (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<DeliverabilityTestPageDto>> getDeliverabilityTests(
        boost::optional<int32_t> page,
        boost::optional<int32_t> size,
        boost::optional<utility::string_t> sort
    ) const;
    /// <summary>
    /// Get latest deliverability simulation job
    /// </summary>
    /// <remarks>
    /// Get the most recent simulation job for a deliverability test.
    /// </remarks>
    /// <param name="testId"></param>
    pplx::task<std::shared_ptr<DeliverabilitySimulationJobDto>> getLatestDeliverabilitySimulationJob(
        utility::string_t testId
    ) const;
    /// <summary>
    /// Pause deliverability simulation job
    /// </summary>
    /// <remarks>
    /// Pause a running simulation job.
    /// </remarks>
    /// <param name="testId"></param>
    /// <param name="jobId"></param>
    pplx::task<std::shared_ptr<DeliverabilitySimulationJobDto>> pauseDeliverabilitySimulationJob(
        utility::string_t testId,
        utility::string_t jobId
    ) const;
    /// <summary>
    /// Pause deliverability/load test
    /// </summary>
    /// <remarks>
    /// Pause a RUNNING or SCHEDULED deliverability test.
    /// </remarks>
    /// <param name="testId"></param>
    pplx::task<std::shared_ptr<DeliverabilityTestDto>> pauseDeliverabilityTest(
        utility::string_t testId
    ) const;
    /// <summary>
    /// Poll deliverability/load test status
    /// </summary>
    /// <remarks>
    /// Poll test progress. Evaluation is throttled with a 5-second cache window to protect backing data stores.
    /// </remarks>
    /// <param name="testId"></param>
    pplx::task<std::shared_ptr<DeliverabilityPollStatusResultDto>> pollDeliverabilityTestStatus(
        utility::string_t testId
    ) const;
    /// <summary>
    /// Resume deliverability simulation job
    /// </summary>
    /// <remarks>
    /// Resume a paused simulation job.
    /// </remarks>
    /// <param name="testId"></param>
    /// <param name="jobId"></param>
    pplx::task<std::shared_ptr<DeliverabilitySimulationJobDto>> resumeDeliverabilitySimulationJob(
        utility::string_t testId,
        utility::string_t jobId
    ) const;
    /// <summary>
    /// Start or resume deliverability/load test
    /// </summary>
    /// <remarks>
    /// Start a CREATED test or resume a PAUSED/SCHEDULED test.
    /// </remarks>
    /// <param name="testId"></param>
    pplx::task<std::shared_ptr<DeliverabilityTestDto>> startDeliverabilityTest(
        utility::string_t testId
    ) const;
    /// <summary>
    /// Stop deliverability/load test
    /// </summary>
    /// <remarks>
    /// Stop a deliverability test and mark it terminal.
    /// </remarks>
    /// <param name="testId"></param>
    pplx::task<std::shared_ptr<DeliverabilityTestDto>> stopDeliverabilityTest(
        utility::string_t testId
    ) const;
    /// <summary>
    /// Update deliverability/load test
    /// </summary>
    /// <remarks>
    /// Update metadata, timeout, and expectations for a non-running non-terminal test.
    /// </remarks>
    /// <param name="testId"></param>
    /// <param name="updateDeliverabilityTestOptions"></param>
    pplx::task<std::shared_ptr<DeliverabilityTestDto>> updateDeliverabilityTest(
        utility::string_t testId,
        std::shared_ptr<UpdateDeliverabilityTestOptions> updateDeliverabilityTestOptions
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* COM_MAILSLURP_CLIENT_API_DeliverabilityTestControllerApi_H_ */

