/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AnalyzeEmailHeadersResults.h
 *
 * 
 */

#ifndef COM_MAILSLURP_CLIENT_MODEL_AnalyzeEmailHeadersResults_H_
#define COM_MAILSLURP_CLIENT_MODEL_AnalyzeEmailHeadersResults_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/EmailHeaderReceivedHop.h"
#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/EmailHeaderAnalysisSummary.h"
#include <map>
#include <vector>

namespace com {
namespace mailslurp {
namespace client {
namespace model {

class EmailHeaderAnalysisSummary;
class EmailHeaderReceivedHop;

/// <summary>
/// 
/// </summary>
class  AnalyzeEmailHeadersResults
    : public ModelBase
{
public:
    AnalyzeEmailHeadersResults();
    virtual ~AnalyzeEmailHeadersResults();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AnalyzeEmailHeadersResults members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<EmailHeaderAnalysisSummary> getSummary() const;
    bool summaryIsSet() const;
    void unsetSummary();

    void setSummary(const std::shared_ptr<EmailHeaderAnalysisSummary>& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<EmailHeaderReceivedHop>>& getReceivedPath();
    bool receivedPathIsSet() const;
    void unsetReceivedPath();

    void setReceivedPath(const std::vector<std::shared_ptr<EmailHeaderReceivedHop>>& value);

    /// <summary>
    /// 
    /// </summary>
    std::map<utility::string_t, std::vector<utility::string_t>>& getParsedHeaders();
    bool parsedHeadersIsSet() const;
    void unsetParsedHeaders();

    void setParsedHeaders(const std::map<utility::string_t, std::vector<utility::string_t>>& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getWarnings();
    bool warningsIsSet() const;
    void unsetWarnings();

    void setWarnings(const std::vector<utility::string_t>& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getErrors();
    bool errorsIsSet() const;
    void unsetErrors();

    void setErrors(const std::vector<utility::string_t>& value);


protected:
    std::shared_ptr<EmailHeaderAnalysisSummary> m_Summary;
    bool m_SummaryIsSet;
    std::vector<std::shared_ptr<EmailHeaderReceivedHop>> m_ReceivedPath;
    bool m_ReceivedPathIsSet;
    std::map<utility::string_t, std::vector<utility::string_t>> m_ParsedHeaders;
    bool m_ParsedHeadersIsSet;
    std::vector<utility::string_t> m_Warnings;
    bool m_WarningsIsSet;
    std::vector<utility::string_t> m_Errors;
    bool m_ErrorsIsSet;
};


}
}
}
}

#endif /* COM_MAILSLURP_CLIENT_MODEL_AnalyzeEmailHeadersResults_H_ */
