/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CreateDomainMonitorOptions.h
 *
 * Create options for a domain monitor
 */

#ifndef COM_MAILSLURP_CLIENT_MODEL_CreateDomainMonitorOptions_H_
#define COM_MAILSLURP_CLIENT_MODEL_CreateDomainMonitorOptions_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace mailslurp {
namespace client {
namespace model {


/// <summary>
/// Create options for a domain monitor
/// </summary>
class  CreateDomainMonitorOptions
    : public ModelBase
{
public:
    CreateDomainMonitorOptions();
    virtual ~CreateDomainMonitorOptions();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CreateDomainMonitorOptions members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDomain() const;
    bool domainIsSet() const;
    void unsetDomain();

    void setDomain(const utility::string_t& value);

    /// <summary>
    /// Optional display name
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();

    void setName(const utility::string_t& value);

    /// <summary>
    /// Check interval in seconds
    /// </summary>
    int64_t getIntervalSeconds() const;
    bool intervalSecondsIsSet() const;
    void unsetIntervalSeconds();

    void setIntervalSeconds(int64_t value);

    /// <summary>
    /// Whether scheduled monitor runs are enabled (legacy alias for schedulingEnabled)
    /// </summary>
    bool isEnabled() const;
    bool enabledIsSet() const;
    void unsetEnabled();

    void setEnabled(bool value);

    /// <summary>
    /// Whether scheduled monitor runs are enabled. Direct run-now is always permitted.
    /// </summary>
    bool isSchedulingEnabled() const;
    bool schedulingEnabledIsSet() const;
    void unsetSchedulingEnabled();

    void setSchedulingEnabled(bool value);


protected:
    utility::string_t m_Domain;
    bool m_DomainIsSet;
    utility::string_t m_Name;
    bool m_NameIsSet;
    int64_t m_IntervalSeconds;
    bool m_IntervalSecondsIsSet;
    bool m_Enabled;
    bool m_EnabledIsSet;
    bool m_SchedulingEnabled;
    bool m_SchedulingEnabledIsSet;
};


}
}
}
}

#endif /* COM_MAILSLURP_CLIENT_MODEL_CreateDomainMonitorOptions_H_ */
