/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DomainMonitorInsightsDto.h
 *
 * 
 */

#ifndef COM_MAILSLURP_CLIENT_MODEL_DomainMonitorInsightsDto_H_
#define COM_MAILSLURP_CLIENT_MODEL_DomainMonitorInsightsDto_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/DomainMonitorRunDto.h"
#include <vector>

namespace com {
namespace mailslurp {
namespace client {
namespace model {

class DomainMonitorRunDto;

/// <summary>
/// 
/// </summary>
class  DomainMonitorInsightsDto
    : public ModelBase
{
public:
    DomainMonitorInsightsDto();
    virtual ~DomainMonitorInsightsDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DomainMonitorInsightsDto members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getMonitorId() const;
    bool monitorIdIsSet() const;
    void unsetMonitorId();

    void setMonitorId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getSince() const;
    bool sinceIsSet() const;
    void unsetSince();

    void setSince(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getBefore() const;
    bool beforeIsSet() const;
    void unsetBefore();

    void setBefore(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getTotalRuns() const;
    bool totalRunsIsSet() const;
    void unsetTotalRuns();

    void setTotalRuns(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getHealthyRuns() const;
    bool healthyRunsIsSet() const;
    void unsetHealthyRuns();

    void setHealthyRuns(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getDegradedRuns() const;
    bool degradedRunsIsSet() const;
    void unsetDegradedRuns();

    void setDegradedRuns(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getCriticalRuns() const;
    bool criticalRunsIsSet() const;
    void unsetCriticalRuns();

    void setCriticalRuns(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getFailedRuns() const;
    bool failedRunsIsSet() const;
    void unsetFailedRuns();

    void setFailedRuns(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    double getSuccessRate() const;
    bool successRateIsSet() const;
    void unsetSuccessRate();

    void setSuccessRate(double value);

    /// <summary>
    /// 
    /// </summary>
    double getAverageHealthScore() const;
    bool averageHealthScoreIsSet() const;
    void unsetAverageHealthScore();

    void setAverageHealthScore(double value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getCurrentHealthyStreak() const;
    bool currentHealthyStreakIsSet() const;
    void unsetCurrentHealthyStreak();

    void setCurrentHealthyStreak(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getBestHealthyStreak() const;
    bool bestHealthyStreakIsSet() const;
    void unsetBestHealthyStreak();

    void setBestHealthyStreak(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getGoodPerformanceSignals();
    bool goodPerformanceSignalsIsSet() const;
    void unsetGoodPerformanceSignals();

    void setGoodPerformanceSignals(const std::vector<utility::string_t>& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getAttentionSignals();
    bool attentionSignalsIsSet() const;
    void unsetAttentionSignals();

    void setAttentionSignals(const std::vector<utility::string_t>& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getTopFindings();
    bool topFindingsIsSet() const;
    void unsetTopFindings();

    void setTopFindings(const std::vector<utility::string_t>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<DomainMonitorRunDto> getLatestRun() const;
    bool latestRunIsSet() const;
    void unsetLatestRun();

    void setLatestRun(const std::shared_ptr<DomainMonitorRunDto>& value);


protected:
    utility::string_t m_MonitorId;
    bool m_MonitorIdIsSet;
    utility::datetime m_Since;
    bool m_SinceIsSet;
    utility::datetime m_Before;
    bool m_BeforeIsSet;
    int32_t m_TotalRuns;
    bool m_TotalRunsIsSet;
    int32_t m_HealthyRuns;
    bool m_HealthyRunsIsSet;
    int32_t m_DegradedRuns;
    bool m_DegradedRunsIsSet;
    int32_t m_CriticalRuns;
    bool m_CriticalRunsIsSet;
    int32_t m_FailedRuns;
    bool m_FailedRunsIsSet;
    double m_SuccessRate;
    bool m_SuccessRateIsSet;
    double m_AverageHealthScore;
    bool m_AverageHealthScoreIsSet;
    int32_t m_CurrentHealthyStreak;
    bool m_CurrentHealthyStreakIsSet;
    int32_t m_BestHealthyStreak;
    bool m_BestHealthyStreakIsSet;
    std::vector<utility::string_t> m_GoodPerformanceSignals;
    bool m_GoodPerformanceSignalsIsSet;
    std::vector<utility::string_t> m_AttentionSignals;
    bool m_AttentionSignalsIsSet;
    std::vector<utility::string_t> m_TopFindings;
    bool m_TopFindingsIsSet;
    std::shared_ptr<DomainMonitorRunDto> m_LatestRun;
    bool m_LatestRunIsSet;
};


}
}
}
}

#endif /* COM_MAILSLURP_CLIENT_MODEL_DomainMonitorInsightsDto_H_ */
