/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DomainMonitorRunDto.h
 *
 * 
 */

#ifndef COM_MAILSLURP_CLIENT_MODEL_DomainMonitorRunDto_H_
#define COM_MAILSLURP_CLIENT_MODEL_DomainMonitorRunDto_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace com {
namespace mailslurp {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  DomainMonitorRunDto
    : public ModelBase
{
public:
    DomainMonitorRunDto();
    virtual ~DomainMonitorRunDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DomainMonitorRunDto members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getMonitorId() const;
    bool monitorIdIsSet() const;
    void unsetMonitorId();

    void setMonitorId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUserId() const;
    bool userIdIsSet() const;
    void unsetUserId();

    void setUserId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDomain() const;
    bool domainIsSet() const;
    void unsetDomain();

    void setDomain(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();

    void setStatus(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTriggerSource() const;
    bool triggerSourceIsSet() const;
    void unsetTriggerSource();

    void setTriggerSource(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getHealthScore() const;
    bool healthScoreIsSet() const;
    void unsetHealthScore();

    void setHealthScore(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getTotalChecks() const;
    bool totalChecksIsSet() const;
    void unsetTotalChecks();

    void setTotalChecks(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getPassingChecks() const;
    bool passingChecksIsSet() const;
    void unsetPassingChecks();

    void setPassingChecks(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getFailingChecks() const;
    bool failingChecksIsSet() const;
    void unsetFailingChecks();

    void setFailingChecks(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    bool isSpfOk() const;
    bool spfOkIsSet() const;
    void unsetSpfOk();

    void setSpfOk(bool value);

    /// <summary>
    /// 
    /// </summary>
    bool isDmarcOk() const;
    bool dmarcOkIsSet() const;
    void unsetDmarcOk();

    void setDmarcOk(bool value);

    /// <summary>
    /// 
    /// </summary>
    bool isDmarcEnforced() const;
    bool dmarcEnforcedIsSet() const;
    void unsetDmarcEnforced();

    void setDmarcEnforced(bool value);

    /// <summary>
    /// 
    /// </summary>
    bool isMxOk() const;
    bool mxOkIsSet() const;
    void unsetMxOk();

    void setMxOk(bool value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getInsights();
    bool insightsIsSet() const;
    void unsetInsights();

    void setInsights(const std::vector<utility::string_t>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getErrorMessage() const;
    bool errorMessageIsSet() const;
    void unsetErrorMessage();

    void setErrorMessage(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();

    void setCreatedAt(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getUpdatedAt() const;
    bool updatedAtIsSet() const;
    void unsetUpdatedAt();

    void setUpdatedAt(const utility::datetime& value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;
    utility::string_t m_MonitorId;
    bool m_MonitorIdIsSet;
    utility::string_t m_UserId;
    bool m_UserIdIsSet;
    utility::string_t m_Domain;
    bool m_DomainIsSet;
    utility::string_t m_Status;
    bool m_StatusIsSet;
    utility::string_t m_TriggerSource;
    bool m_TriggerSourceIsSet;
    int32_t m_HealthScore;
    bool m_HealthScoreIsSet;
    int32_t m_TotalChecks;
    bool m_TotalChecksIsSet;
    int32_t m_PassingChecks;
    bool m_PassingChecksIsSet;
    int32_t m_FailingChecks;
    bool m_FailingChecksIsSet;
    bool m_SpfOk;
    bool m_SpfOkIsSet;
    bool m_DmarcOk;
    bool m_DmarcOkIsSet;
    bool m_DmarcEnforced;
    bool m_DmarcEnforcedIsSet;
    bool m_MxOk;
    bool m_MxOkIsSet;
    std::vector<utility::string_t> m_Insights;
    bool m_InsightsIsSet;
    utility::string_t m_ErrorMessage;
    bool m_ErrorMessageIsSet;
    utility::datetime m_CreatedAt;
    bool m_CreatedAtIsSet;
    utility::datetime m_UpdatedAt;
    bool m_UpdatedAtIsSet;
};


}
}
}
}

#endif /* COM_MAILSLURP_CLIENT_MODEL_DomainMonitorRunDto_H_ */
