/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TestSmtpServerOptions.h
 *
 * 
 */

#ifndef COM_MAILSLURP_CLIENT_MODEL_TestSmtpServerOptions_H_
#define COM_MAILSLURP_CLIENT_MODEL_TestSmtpServerOptions_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace mailslurp {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  TestSmtpServerOptions
    : public ModelBase
{
public:
    TestSmtpServerOptions();
    virtual ~TestSmtpServerOptions();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TestSmtpServerOptions members

    /// <summary>
    /// SMTP host name or IP address
    /// </summary>
    utility::string_t getHost() const;
    bool hostIsSet() const;
    void unsetHost();

    void setHost(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getPort() const;
    bool portIsSet() const;
    void unsetPort();

    void setPort(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    bool isUseStartTls() const;
    bool useStartTlsIsSet() const;
    void unsetUseStartTls();

    void setUseStartTls(bool value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUsername() const;
    bool usernameIsSet() const;
    void unsetUsername();

    void setUsername(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPassword() const;
    bool passwordIsSet() const;
    void unsetPassword();

    void setPassword(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getFrom() const;
    bool fromIsSet() const;
    void unsetFrom();

    void setFrom(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTo() const;
    bool toIsSet() const;
    void unsetTo();

    void setTo(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getCaptchaToken() const;
    bool captchaTokenIsSet() const;
    void unsetCaptchaToken();

    void setCaptchaToken(const utility::string_t& value);


protected:
    utility::string_t m_Host;
    bool m_HostIsSet;
    int32_t m_Port;
    bool m_PortIsSet;
    bool m_UseStartTls;
    bool m_UseStartTlsIsSet;
    utility::string_t m_Username;
    bool m_UsernameIsSet;
    utility::string_t m_Password;
    bool m_PasswordIsSet;
    utility::string_t m_From;
    bool m_FromIsSet;
    utility::string_t m_To;
    bool m_ToIsSet;
    utility::string_t m_CaptchaToken;
    bool m_CaptchaTokenIsSet;
};


}
}
}
}

#endif /* COM_MAILSLURP_CLIENT_MODEL_TestSmtpServerOptions_H_ */
