/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/CancelDevicePreviewRunResult.h"

namespace com {
namespace mailslurp {
namespace client {
namespace model {



CancelDevicePreviewRunResult::CancelDevicePreviewRunResult()
{
    m_RunIsSet = false;
    m_RemoteCancelAttempted = false;
    m_RemoteCancelAttemptedIsSet = false;
    m_RemoteCancelAccepted = false;
    m_RemoteCancelAcceptedIsSet = false;
    m_Warning = utility::conversions::to_string_t("");
    m_WarningIsSet = false;
}

CancelDevicePreviewRunResult::~CancelDevicePreviewRunResult()
{
}

void CancelDevicePreviewRunResult::validate()
{
    // TODO: implement validation
}

web::json::value CancelDevicePreviewRunResult::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_RunIsSet)
    {
        val[utility::conversions::to_string_t(U("run"))] = ModelBase::toJson(m_Run);
    }
    if(m_RemoteCancelAttemptedIsSet)
    {
        val[utility::conversions::to_string_t(U("remoteCancelAttempted"))] = ModelBase::toJson(m_RemoteCancelAttempted);
    }
    if(m_RemoteCancelAcceptedIsSet)
    {
        val[utility::conversions::to_string_t(U("remoteCancelAccepted"))] = ModelBase::toJson(m_RemoteCancelAccepted);
    }
    if(m_WarningIsSet)
    {
        val[utility::conversions::to_string_t(U("warning"))] = ModelBase::toJson(m_Warning);
    }

    return val;
}

bool CancelDevicePreviewRunResult::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("run"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("run")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<DevicePreviewRunDto> refVal_setRun;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRun);
            setRun(refVal_setRun);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("remoteCancelAttempted"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("remoteCancelAttempted")));
        if(!fieldValue.is_null())
        {
            bool refVal_setRemoteCancelAttempted;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRemoteCancelAttempted);
            setRemoteCancelAttempted(refVal_setRemoteCancelAttempted);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("remoteCancelAccepted"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("remoteCancelAccepted")));
        if(!fieldValue.is_null())
        {
            bool refVal_setRemoteCancelAccepted;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRemoteCancelAccepted);
            setRemoteCancelAccepted(refVal_setRemoteCancelAccepted);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("warning"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("warning")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWarning;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWarning);
            setWarning(refVal_setWarning);
        }
    }
    return ok;
}

void CancelDevicePreviewRunResult::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_RunIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("run")), m_Run));
    }
    if(m_RemoteCancelAttemptedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("remoteCancelAttempted")), m_RemoteCancelAttempted));
    }
    if(m_RemoteCancelAcceptedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("remoteCancelAccepted")), m_RemoteCancelAccepted));
    }
    if(m_WarningIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("warning")), m_Warning));
    }
}

bool CancelDevicePreviewRunResult::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("run"))))
    {
        std::shared_ptr<DevicePreviewRunDto> refVal_setRun;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("run"))), refVal_setRun );
        setRun(refVal_setRun);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("remoteCancelAttempted"))))
    {
        bool refVal_setRemoteCancelAttempted;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("remoteCancelAttempted"))), refVal_setRemoteCancelAttempted );
        setRemoteCancelAttempted(refVal_setRemoteCancelAttempted);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("remoteCancelAccepted"))))
    {
        bool refVal_setRemoteCancelAccepted;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("remoteCancelAccepted"))), refVal_setRemoteCancelAccepted );
        setRemoteCancelAccepted(refVal_setRemoteCancelAccepted);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("warning"))))
    {
        utility::string_t refVal_setWarning;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("warning"))), refVal_setWarning );
        setWarning(refVal_setWarning);
    }
    return ok;
}

std::shared_ptr<DevicePreviewRunDto> CancelDevicePreviewRunResult::getRun() const
{
    return m_Run;
}

void CancelDevicePreviewRunResult::setRun(const std::shared_ptr<DevicePreviewRunDto>& value)
{
    m_Run = value;
    m_RunIsSet = true;
}

bool CancelDevicePreviewRunResult::runIsSet() const
{
    return m_RunIsSet;
}

void CancelDevicePreviewRunResult::unsetRun()
{
    m_RunIsSet = false;
}
bool CancelDevicePreviewRunResult::isRemoteCancelAttempted() const
{
    return m_RemoteCancelAttempted;
}

void CancelDevicePreviewRunResult::setRemoteCancelAttempted(bool value)
{
    m_RemoteCancelAttempted = value;
    m_RemoteCancelAttemptedIsSet = true;
}

bool CancelDevicePreviewRunResult::remoteCancelAttemptedIsSet() const
{
    return m_RemoteCancelAttemptedIsSet;
}

void CancelDevicePreviewRunResult::unsetRemoteCancelAttempted()
{
    m_RemoteCancelAttemptedIsSet = false;
}
bool CancelDevicePreviewRunResult::isRemoteCancelAccepted() const
{
    return m_RemoteCancelAccepted;
}

void CancelDevicePreviewRunResult::setRemoteCancelAccepted(bool value)
{
    m_RemoteCancelAccepted = value;
    m_RemoteCancelAcceptedIsSet = true;
}

bool CancelDevicePreviewRunResult::remoteCancelAcceptedIsSet() const
{
    return m_RemoteCancelAcceptedIsSet;
}

void CancelDevicePreviewRunResult::unsetRemoteCancelAccepted()
{
    m_RemoteCancelAcceptedIsSet = false;
}
utility::string_t CancelDevicePreviewRunResult::getWarning() const
{
    return m_Warning;
}

void CancelDevicePreviewRunResult::setWarning(const utility::string_t& value)
{
    m_Warning = value;
    m_WarningIsSet = true;
}

bool CancelDevicePreviewRunResult::warningIsSet() const
{
    return m_WarningIsSet;
}

void CancelDevicePreviewRunResult::unsetWarning()
{
    m_WarningIsSet = false;
}
}
}
}
}


