/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ExtractAttachmentTextOptions.h"

namespace com {
namespace mailslurp {
namespace client {
namespace model {



ExtractAttachmentTextOptions::ExtractAttachmentTextOptions()
{
    m_Method = utility::conversions::to_string_t("");
    m_MethodIsSet = false;
    m_AllowFallback = false;
    m_AllowFallbackIsSet = false;
    m_MaxBytes = 0L;
    m_MaxBytesIsSet = false;
}

ExtractAttachmentTextOptions::~ExtractAttachmentTextOptions()
{
}

void ExtractAttachmentTextOptions::validate()
{
    // TODO: implement validation
}

web::json::value ExtractAttachmentTextOptions::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_MethodIsSet)
    {
        val[utility::conversions::to_string_t(U("method"))] = ModelBase::toJson(m_Method);
    }
    if(m_AllowFallbackIsSet)
    {
        val[utility::conversions::to_string_t(U("allowFallback"))] = ModelBase::toJson(m_AllowFallback);
    }
    if(m_MaxBytesIsSet)
    {
        val[utility::conversions::to_string_t(U("maxBytes"))] = ModelBase::toJson(m_MaxBytes);
    }

    return val;
}

bool ExtractAttachmentTextOptions::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("method"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("method")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMethod;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMethod);
            setMethod(refVal_setMethod);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("allowFallback"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("allowFallback")));
        if(!fieldValue.is_null())
        {
            bool refVal_setAllowFallback;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAllowFallback);
            setAllowFallback(refVal_setAllowFallback);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("maxBytes"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("maxBytes")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setMaxBytes;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMaxBytes);
            setMaxBytes(refVal_setMaxBytes);
        }
    }
    return ok;
}

void ExtractAttachmentTextOptions::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_MethodIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("method")), m_Method));
    }
    if(m_AllowFallbackIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("allowFallback")), m_AllowFallback));
    }
    if(m_MaxBytesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("maxBytes")), m_MaxBytes));
    }
}

bool ExtractAttachmentTextOptions::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("method"))))
    {
        utility::string_t refVal_setMethod;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("method"))), refVal_setMethod );
        setMethod(refVal_setMethod);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("allowFallback"))))
    {
        bool refVal_setAllowFallback;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("allowFallback"))), refVal_setAllowFallback );
        setAllowFallback(refVal_setAllowFallback);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("maxBytes"))))
    {
        int64_t refVal_setMaxBytes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("maxBytes"))), refVal_setMaxBytes );
        setMaxBytes(refVal_setMaxBytes);
    }
    return ok;
}

utility::string_t ExtractAttachmentTextOptions::getMethod() const
{
    return m_Method;
}

void ExtractAttachmentTextOptions::setMethod(const utility::string_t& value)
{
    m_Method = value;
    m_MethodIsSet = true;
}

bool ExtractAttachmentTextOptions::methodIsSet() const
{
    return m_MethodIsSet;
}

void ExtractAttachmentTextOptions::unsetMethod()
{
    m_MethodIsSet = false;
}
bool ExtractAttachmentTextOptions::isAllowFallback() const
{
    return m_AllowFallback;
}

void ExtractAttachmentTextOptions::setAllowFallback(bool value)
{
    m_AllowFallback = value;
    m_AllowFallbackIsSet = true;
}

bool ExtractAttachmentTextOptions::allowFallbackIsSet() const
{
    return m_AllowFallbackIsSet;
}

void ExtractAttachmentTextOptions::unsetAllowFallback()
{
    m_AllowFallbackIsSet = false;
}
int64_t ExtractAttachmentTextOptions::getMaxBytes() const
{
    return m_MaxBytes;
}

void ExtractAttachmentTextOptions::setMaxBytes(int64_t value)
{
    m_MaxBytes = value;
    m_MaxBytesIsSet = true;
}

bool ExtractAttachmentTextOptions::maxBytesIsSet() const
{
    return m_MaxBytesIsSet;
}

void ExtractAttachmentTextOptions::unsetMaxBytes()
{
    m_MaxBytesIsSet = false;
}
}
}
}
}


